apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: rest-app-b
    version: v1
  name: rest-app-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-app-b
      version: v1
  template:
    metadata:
      labels:
        app: rest-app-b
        group: tutorial-rest-app
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - env:
            - name: JAVA_OPTIONS
              value: -Xms128m -Xmx128m -Xmn128m
          name: rest-app-b
          image: image-registry.openshift-image-registry.svc:5000/tutorial/rest-app-b
#          image: default-route-openshift-image-registry.apps-crc.testing/tutorial/rest-app-b
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: "200m" # 1/5 core
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          securityContext:
            privileged: false