apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: rest-app-no-istio
    version: v1
  name: rest-app-no-istio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-app-no-istio
      version: v1
  template:
    metadata:
      labels:
        app: rest-app-no-istio
        group: tutorial-rest-app
        version: v1
      annotations:
    spec:
      containers:
        - env:
            - name: JAVA_OPTIONS
              value: -Xms128m -Xmx128m -Xmn128m
          name: rest-app-no-istio
          image: image-registry.openshift-image-registry.svc:5000/tutorial/rest-app-b
#          image: default-route-openshift-image-registry.apps-crc.testing/tutorial/rest-app-no-istio
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: "200m" # 1/5 core
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          securityContext:
            privileged: false