apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rest-app-a
    version: v1
  name: rest-app-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-app-a
      version: v1
  template:
    metadata:
      labels:
        app: rest-app-a
        group: tutorial-rest-app
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - env:
            - name: JAVA_OPTIONS
              value: -Xms128m -Xmx128m -Xmn128m
            - name: SERVICE_B_URI
              valueFrom:
                configMapKeyRef:
                  name: rest-app-config
                  key: service.b.uri
          name: jdbc-app-1
          image: image-registry.openshift-image-registry.svc:5000/tutorial/rest-app-a
          #image: default-route-openshift-image-registry.apps-crc.testing/tutorial/rest-app-a
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m" # 1/5 core
            limits:
              memory: "400Mi"
              cpu: "500m"
          securityContext:
            privileged: false